### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Lzyin** [lxa9867/QSD#2]
Thank you for your interesting work!

When will the code be released?

**Comment by lxa9867** [comment]
Thanks for your interest. Unfortunately, due to the company policy, I was unable to release the code eventually. 

If you are interested in implement the PQ in your code, you can start from the taming transformer’s VQ implementation. We basically borrow their VQ for the PQ implementation. Please feel free to reach out here if you have any questions.

**Comment by Lzyin** [comment]
Yeah, I am very interested in the content of Section 3.1. Is the implementation of PQ related to the paper "Taming Transformers for High-Resolution Image Synthesis"? Alternatively, is it possible to release just this part of the code?

Thank you for your reply.

**Comment by lxa9867** [comment]
The implementation is pretty easy, as you may just copy the VQ operation from [https://github.com/CompVis/taming-transformers/blob/master/taming/modules/vqvae/quantize.py](VQGAN), call it multiple times, and then concat the outputs.

**Comment by Lzyin** [comment]
I got it, thanks a lot!
